services:
  - type: web
    name: eaglercraft-119-server
    env: docker
    repo: https://github.com/kabonk1/SHE-mc-server.git   # またはあなたのFork
    branch: main
    plan: free
    numInstances: 1
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: JAVA_OPTS
        value: "-Dlog4j2.formatMsgNoLookups=true"


